---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - MySiteConfigExtension
SilverStripe\View\SSViewer:
  themes:
    - mysite
BetterButtonsActions:
  create:
    BetterButton_Save: true
    BetterButton_SaveAndClose: true
    BetterButton_SaveAndAdd: true
  edit:
    BetterButton_Save: true
    BetterButton_SaveAndClose: true
    BetterButton_SaveAndAdd: true
    BetterButton_Delete: true
    BetterButtonFrontendLinksAction: true